remote_theme: pages-themes/minimal@v0.2.0
logo: /assets/MainLogo.png
title: Kayla Elizabeth Campana, Texts & Technology PhD Student
description: Kayla Elizabeth Campana, Texts & Technology PhD Student