# Your Name or Company
title: Kayla Elizabeth Campana

# Description of your website. This is used for social sharing.
description:  Digital Humanities PhD Student

# A brief blurb about yourself
content: Nullam id dolor id nibh ultricies vehicula ut id elit. Cras mattis consectetur purus sit amet fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mattis consectetur purus sit amet fermentum.

# Add your social links
social:
  - platform: instagram
    url: https://instagram.com/kaylaecampana
  - platform: linkedin
    url: kaylaecampana

# General settings
# url: http://kaylaecampana.github.com/main
# baseurl: "/main" 
markdown: kramdown
sharing_image: share.jpg

#### LAYOUT OPTIONS #####

# Half layout
half_side: left

# Full layout
full_text_position: right # left, right or center
